namespace NavArgs.Generator;

internal static class Constants
{
    internal const string Namespace = "Generators";
    internal const string NavAttributeName = "NavDestinationAttribute";
    internal const string NavInterfaceName = "INavDestination";
    internal const string ArgsInterfaceName = "INavArgs";

    internal const string NavAttributeSourceCode =
        $"""
         // <auto-generated/>
         using System;

         namespace {Namespace};

         [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
         public class {NavAttributeName} : Attribute;
         """;

    internal const string NavInterfaceSourceCode =
        $$"""
          // <auto-generated/>
          namespace {{Namespace}};

          public interface {{NavInterfaceName}}
          {
               public string Route { get; }
               public INavArgs GetArgs();
          }
          """;

    internal const string ArgsInterfaceSourceCode =
        $$"""
          // <auto-generated/>
          using System.Collections.Generic;

          namespace {{Namespace}};

          public interface {{ArgsInterfaceName}}
          {
              IDictionary<string, object> ToDictionary();
          }
          """;
}