namespace NavArgs.Generator;

public partial class NavDestinationGenerator
{
    private const string Namespace = "Generators";
    private const string NavAttributeName = "NavDestinationAttribute";
    private const string NavInterfaceName = "INavDestination";
    private const string ArgsInterfaceName = "INavArgs";

    private const string NavAttributeSourceCode =
        $"""
         // <auto-generated/>
         using System;

         namespace {Namespace};

         [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
         public class {NavAttributeName} : Attribute;
         """;

    private const string NavInterfaceSourceCode =
        $$"""
          // <auto-generated/>
          namespace {{Namespace}};

          public interface {{NavInterfaceName}}
          {
               public string Route { get; }
               public INavArgs GetArgs();
          }
          """;

    private const string ArgsInterfaceSourceCode =
        $$"""
          // <auto-generated/>
          using System.Collections.Generic;
          
          namespace {{Namespace}};

          public interface {{ArgsInterfaceName}}
          {
              IDictionary<string, object> ToDictionary();
          }
          """;
}