namespace NavArgs.Abstractions.Tests;

public static class Constants
{
    public const string AccountDetailsWithoutRouteClass =
        """
        using NavArgs.Abstractions;
        
        namespace UserNamespace;

        [NavDestination]
        public partial class AccountDetails : INavDestination
        {
            public string Route { get; } = "account-details";
            public int Id { get; set };
            public string Name { get; set; }
            public string Email { get; set; }
        }
        """;

    public const string ExpectedAccountDetailsWithoutRouteClass =
        """
        // <auto-generated/>
        #nullable enable
        using System;
        using System.Collections.Generic;
        using NavArgs.Abstractions;
        
        namespace UserNamespace
        {
            partial class AccountDetails
            {
                public INavArgs GetArgs()
                {
                    return new AccountDetailsArgs()
                    {Id = this.Id, Name = this.Name, Email = this.Email};
                }
            }

            // <auto-generated/>
            public sealed class AccountDetailsArgs : INavArgs
            {
                public int Id { get; init; }
                public string Name { get; init; }
                public string Email { get; init; }

                public static AccountDetailsArgs FromDictionary(Dictionary<string, object> dictionary)
                {
                    return new AccountDetailsArgs()
                    {Id = (int)Convert.ChangeType(dictionary[nameof(Id)], typeof(int)), Name = (string)Convert.ChangeType(dictionary[nameof(Name)], typeof(string)), Email = (string)Convert.ChangeType(dictionary[nameof(Email)], typeof(string))};
                }

                public IDictionary<string, object?> ToDictionary()
                {
                    return new Dictionary<string, object?>()
                    {[nameof(Id)] = this.Id, [nameof(Name)] = this.Name, [nameof(Email)] = this.Email};
                }
            }
        }
        """;
}