//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavArgs.Abstractions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavArgs.Abstractions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must implement NavArgs.Abstractions.INavDestination..
        /// </summary>
        internal static string NVA001Description {
            get {
                return ResourceManager.GetString("NVA001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; must implement &apos;{1}&apos;.
        /// </summary>
        internal static string NVA001MessageFormat {
            get {
                return ResourceManager.GetString("NVA001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement NavArgs.Abstractions.INavDestination.
        /// </summary>
        internal static string NVA001Title {
            get {
                return ResourceManager.GetString("NVA001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference types will be annotated as nullable in generated Args class..
        /// </summary>
        internal static string NVA002Description {
            get {
                return ResourceManager.GetString("NVA002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; will be nullable in Associated Args class.
        /// </summary>
        internal static string NVA002MessageFormat {
            get {
                return ResourceManager.GetString("NVA002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property will become nullable.
        /// </summary>
        internal static string NVA002Title {
            get {
                return ResourceManager.GetString("NVA002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute property cannot be null or an empty string..
        /// </summary>
        internal static string NVA003Description {
            get {
                return ResourceManager.GetString("NVA003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} of attribute {1} cannot be null or an empty string.
        /// </summary>
        internal static string NVA003MessageFormat {
            get {
                return ResourceManager.GetString("NVA003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Attribute Property Value.
        /// </summary>
        internal static string NVA003Title {
            get {
                return ResourceManager.GetString("NVA003Title", resourceCulture);
            }
        }
    }
}
